Merge our default develop branch
mugberto/capstone-api-based-web pull request #37
Opened 2021-08-06 11:26 UTC by vladanvi99

In this pull request, we want to merge our default development branch with the main branch.

2021-08-06 19:05 UTC, henatan99 requested changes
Hi @vladanvi99 && @mugberto , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

- Honestly, you guys did a hell of a job. Very organized and clean code. Slick on the user end. I commend you!!! :clap: :clap: :clap: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] All the members in the video should appear in the video and talk about the project. kindly record your video again. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-06 19:05 UTC, henatan99 commented on README.md
> +
- [ ] Please, acknowledge any person or party whom resources are being used or referenced in your project.

2021-08-06 19:05 UTC, henatan99 commented on package.json
> +    "test": "jest",
- [ ] Please, do some workaround with your `test` config as it is complaining on my end and I cannot run the test. 
![Screenshot from 2021-08-07 00-59-55](https://user-images.githubusercontent.com/64894927/128559397-d8eab1b6-e934-4c5b-9cbd-62d14d6b19f5.png)

2021-08-07 13:21 UTC, mugberto commented
Thank you @henatan99 for the review. 
We have made another video as per request. We ran tests on two different operating systems and everything went fine. Maybe some of the dependencies were installed correctly. You can run again `npm install`

2021-08-07 13:44 UTC, bellom approved these changes
## Hi @vladanvi99 @mugberto  👏  

**Great work making all the necessary corrections from the previous review.**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-07 15:48 UTC, merged